### ISSUE TITLE
Chrome Unresponsive

### ISSUE THREAD

**Issue by wirelesshnic** [gnu-lorien/yorick#10]
I am not sure on the cause of this but multiple times during the editing phase, my chrome browser stopped responding.  Reloading the page fixed this issue and any changes that where made where saved.

**Comment by gnu-lorien** [comment]
Do you remember what you were doing each of those times? There was an old bug where the sync/save stack was becoming too complicated and would freeze the browser. I thought I got rid of those. Do you remember about the last five-ish things you were doing before it froze? I suspect you were seeing it more often after saving a change of some kind.

**Comment by wirelesshnic** [comment]
I dont remember right now but I will document it the next time it happens.

**Comment by gnu-lorien** [comment]
I think these were all related to the recursive save problem in the sheet. That particular performance problem should be gone now.
