### ISSUE TITLE
Caitiff and Sabbat related issues (a few)

### ISSUE THREAD

**Issue by LordHylas** [gnu-lorien/yorick#103]
Sabbat related: Merits don't have the correct point values for costs of Paths for Sabbat (Feral Heart and the like should cost 1 point, not 3)

Caitiff/Pander related:
 -Panders not listed in clan selections.
 -Auspicious: No way to tag which merit you purchased with Auspicious
 -Vestiges of Greatness: No way to tag which discipline is the one you selected with merit.
 -Being charged out of clan costs for ALL disciplines, so character point totals are completely wrong.

**Comment by gnu-lorien** [comment]
Mechanically, there is no such thing as a Pander. They are Caitiff by the system.

When you take a merit that augments your in-clan disciplines, you can add in-clan disciplines in the "Extra in-clan disciplines section."

When you are finished with character creation, you can go to the individual merit and modify it with a "Specialize Name" to specify what you did with it.

**Comment by gnu-lorien** [comment]
#104 is a link task and I'm working on documentation now to hopefully smooth this in the future.
