### ISSUE TITLE
FB not Connecting

### ISSUE THREAD

**Issue by LatisDreams** [gnu-lorien/yorick#112]
Tried to attach my FB to the account again with this Error Reported: 
"400 Bad Request: POST https://api.undergroundtheater.org/parse/1/classes/_User/RWrSoVBCLq"
(Amber Godat's account linked to larping@live.com)

**Comment by gnu-lorien** [comment]
"Tried to attach"

You hit the log in with Facebook button, or you tried to connect the two in your profile for a second time? Show me a screenshot if you can of what you did.

**Comment by LatisDreams** [comment]
Ok, so I logged into my account and went to the profile page (https://yorick.pubstorm.site/#profile).
At the bottom where it says "Link account to FB," that's what I clicked:

![fb attach issue 1](https://cloud.githubusercontent.com/assets/20496132/16903460/c249ad8e-4c4c-11e6-92b0-d4d8b7db9c2d.jpg)
When I click on the add FB "button," this was the result: 
![fb attach issue 2](https://cloud.githubusercontent.com/assets/20496132/16903475/31990e1e-4c4d-11e6-8123-62b4edeb9f7e.jpg)



Now, when you first added the feature, I did click the "Log in with FB" button on the Home page, thinking it would have a place for me to link FB to my already existing account, but it looks like it may have auto set up another: 
![fb attach issue 3](https://cloud.githubusercontent.com/assets/20496132/16903492/f2e0661c-4c4d-11e6-88d1-71f7f6443f20.jpg)



If so, is there a way to merge the two? If that's not what's occurred, I've no clue what to do now, not that it's needed. I was just curious about the function.

**Comment by LatisDreams** [comment]
I'm actually thinking now to just change the email of the primary account to use the secretary email and then attach my characters to the FB account (one indeed has already been made). This way, once someone takes over the office from me, they'd only need to change the username and personal info. That is... if those things can be changed? What do you think is best?

**Comment by gnu-lorien** [comment]
Yes do it that way. I can change account linkings like that pretty easily once they're set up. The thing that is *hard* to change is which one is associated with facebook. Do the email swap thing you're talking about and I think everything will be fine.
