### ISSUE TITLE
Minor quirks and things missing.

### ISSUE THREAD

**Issue by Octave84** [gnu-lorien/yorick#121]
I found a few minor issues. First is there are no Independent Alliance titles. I also found that I can't take Necromantic Expertise twice. I took Necromantic Insight to cover it for now. Last is whenever I have to add a custom specialization, it kicks me pack to the character generation page. Like I said, nothing major, just wanted to let you know what I came across.

**Comment by gnu-lorien** [comment]
I didn't see any Independent Alliance titles in the book last time I checked. Are they in there somewhere and I missed them? If you get me a list of them I can add them. #123

You can take Necromantic Expertise twice. https://github.com/gnu-lorien/yorick/wiki/FAQ#magical-expertise-merits-thaumaturgical-expertise-and-necromantic-expertise

Filed #122 for the specialization redirect bit. Somebody had reported it once before but I didn't really understand what was happening. Now it makes sense.

**Comment by gnu-lorien** [comment]
I suspect you were tripped on Necromantic Expertise by #107. I'll count this as a "vote" to raise the priority on that one.

**Comment by Octave84** [comment]
Don/Dona (Giovanni): The Don (or Dona) serves as the clan leader for the Giovanni within a city.

Hierophant (Followers of Set): The Hierophant acts as the clan leader and religious head of the Followers of Set in a city.

Emissary: In each domain that the Alliance is present, each clan appoints an Emissary to the other. The Emissary serves as witness to any notable dealings with the other clan and serves as arbiter to any disputes between them.
These are found in the Underground Theater Independent Alliance Setting Packet. There is also one for the Ravnos.

**Comment by Octave84** [comment]
Rom baro/Netaji (Ravnos): The Rom baro or Netaji serves as the family head of the Ravnos within a city. The position is chosen amongst the local Ravnos based on an individual’s merit, resourcefulness, and local area knowledge.
Here is the Ravnos title.

**Comment by gnu-lorien** [comment]
Added
