### ISSUE TITLE
Stuck on Loading - Mobile

### ISSUE THREAD

**Issue by kingolaf82** [gnu-lorien/yorick#129]
Yorick will not load on mobile (iPhone 6 9.3.4)

**Comment by gnu-lorien** [comment]
Looks like this is related to timeouts over mobile connections. In particular, it's almost always this one:
```
 Load timeout for modules: vis
 http://requirejs.org/docs/errors.html#timeout
```

Does the test version of the site load for you? http://yorick.pubstorm.site/

I'm going to use this as the tracking bug for better notification when the loading times out, and for trying to improve load times in general.

**Comment by gnu-lorien** [comment]
Reordered for 0.7.6
