### ISSUE TITLE
influences -> elite: no custom specializations

### ISSUE THREAD

**Issue by UTLaCrosseLst** [gnu-lorien/yorick#132]
i am unable to add my specializations for my character because there is not an option to add a custom specializations to the list so if you dont have something from the preset list of examples you can't add anything at all under the specs. You can however have the correct dots.

**Comment by gnu-lorien** [comment]
There is an entry named, "Custom" in the list. If you click on that it lets you set whatever you would like.

**Comment by UTLaCrosseLst** [comment]
Well apparently i am blind. My apologies. it's totally right there too. I was looking along the top for the option. This makes sense though.

**Comment by UTLaCrosseLst** [comment]
Also thank you for your fast response

**Comment by gnu-lorien** [comment]
No problem! Glad I could help.
