### ISSUE TITLE
Remove or hide deleted characters from troupe characters list

### ISSUE THREAD

**Issue by Jenna001** [gnu-lorien/yorick#134]
Can we please add a way to hide or remove deleted characters from the troupe character list? Otherwise that's going to get very cluttered very fast. Thank you.

![capture](https://cloud.githubusercontent.com/assets/14209258/17713956/2de554c0-63c3-11e6-860b-1f059572ef64.JPG)

**Comment by gnu-lorien** [comment]
Reordered for 0.7.6
