### ISSUE TITLE
Error 400 Message.

### ISSUE THREAD

**Issue by Octave84** [gnu-lorien/yorick#140]
I can't sign in to Yorick using facebook on my computer. It is giving me a 400 facebook error message. No idea what to do.
Never mind. It fixed itself.

**Comment by gnu-lorien** [comment]
Try going to this address to force a clean logout: https://patron.undergroundtheater.org/#logout

Can you also send me a screenshot of what you see when it's breaking?

**Comment by gnu-lorien** [comment]
I see it is working now. Good good :+1:
