### ISSUE TITLE
Adding Uncommon and Rare Fera Merits

### ISSUE THREAD

**Issue by ptbrown121** [gnu-lorien/yorick#150]
There are is no 2 point Uncommon Fera merit or a 4 point Rare Fera merit in the list of Werewolf merits.

**Comment by gnu-lorien** [comment]
![image](https://cloud.githubusercontent.com/assets/731/20400139/8fa08bd4-acc1-11e6-82c3-c470d83d8f9a.png)

Added merits to stagingpatron and the spreadsheet I use for imports.
