### ISSUE TITLE
Add Fera camps to wta_camps

### ISSUE THREAD

**Issue by ptbrown121** [gnu-lorien/yorick#160]
The following Fera camps need to be added to wta_camps

Kumoti
Tenere
Hatar
Hermetic Order of the Swift Light
Chasers
Gray Hats
Forest Walkers
Mountain Gaurdians
Okuma
Inari's Messengers
Rusty's Rumspringa
The Wheel
Munchmausen
Twitchers
Engineers
Betweeners
Fury of the Sea
Tainted Consumption

**Comment by gnu-lorien** [comment]
Does this list look right for that data?

![image](https://cloud.githubusercontent.com/assets/731/21598270/dcc86456-d127-11e6-88e8-676fa9a238e4.png)

**Comment by ptbrown121** [comment]
Yep, that is perfect.

**Comment by gnu-lorien** [comment]
Should be updated in live now.
