### ISSUE TITLE
Child of Gaia gifts show up as out of affinity

### ISSUE THREAD

**Issue by ptbrown121** [gnu-lorien/yorick#163]
Child of Gaia gifts are not showing up as in affinity for Child of Gaia characters.  I don't know where the gifts are stored, but I would imagine that there is a disconnect between the name the tribe is called when they are selected, "Children Of Gaia", and the associated name in the gifts data entry.

**Comment by gnu-lorien** [comment]
Wow. Good catch.

The problem was the capital O in "Of." I've fixed the tribe name be lowercase in the Descriptions, and for all of the characters I could find.

**Comment by ptbrown121** [comment]
Credit doesn't fully go to me.  The issue was posted on the Facebook in Yorick help group.
