### ISSUE TITLE
Missing Gift and Wrong Name

### ISSUE THREAD

**Issue by mateo-marshall** [gnu-lorien/yorick#164]
The gift Stoking Fury's Vengeance is labeled as Stoking the Furnace.

The Rank 5 Homid/Ragabash gift The Artful Dodger is not appearing in the gift list for Homid.

**Comment by gnu-lorien** [comment]
Live and Staging
Updated Stoking Fury's Furnace and the characters that had that Gift.
The Artful Dodger wasn't showing up because a lower-case "homid" made it into my description list.

Does it look right now?

**Comment by mateo-marshall** [comment]
XP Values jumped on them to out of affinity but that was a quick XP log fix.  Thanks!
