### ISSUE TITLE
Allow STs to perform searches of troupes by backgrounds, flaws, merits, etc.

### ISSUE THREAD

**Issue by nacustis** [gnu-lorien/yorick#165]
It would be incredibly helpful as an ST to be able to run a search requesting a report of disciplines, flaws, backgrounds, etc, Contacts, Allies, Influences, etc. from a subset of a particular troupe. For instance, "Who in my troupe has Contacts, and what are their specializations?" or "Who in my troupe has Oracular Ability or Nightmares"?

**Comment by gnu-lorien** [comment]
You can already do this on the Summarize Characters page for your Troupe. Check out the release notes https://github.com/gnu-lorien/yorick/releases/tag/v0.7.7

Let me know if there is something missing from that page

**Comment by nacustis** [comment]
Oh wow, thanks a ton! Sorry to suggest something that already existed.
