### ISSUE TITLE
Extended print text not showing up on approved character sheet

### ISSUE THREAD

**Issue by aramahus** [gnu-lorien/yorick#171]
The extended print text will show up on the latest version of the character sheet but when you select the approved version of the character sheet it is no longer there.  From what I could see it doesn't seem to act like a change to the character that goes through the same approval steps that a stat change would go through.

**Comment by gnu-lorien** [comment]
I'll look into fixing this today. It seems like the extended print text that's fetched doesn't persist with the transformed (approved) version of the character.

**Comment by gnu-lorien** [comment]
Should be fixed in live now if you do a full refresh of the page.

**Comment by aramahus** [comment]
Awesome, thanks man.  It is now working without issue.
