### ISSUE TITLE
Stamina focus for Fortitude

### ISSUE THREAD

**Issue by jbdryden** [gnu-lorien/yorick#180]
I noticed an issue -- though perhaps there is a functionality I am missing in trying to resolve it -- related to Fortitude and Stamina. I have chosen Stamina as a Physical focus and have Fortitude as a discipline; however, the extra levels of health that should come from that combination do not show up on the printable character sheet. There also does not seem to be a way to indicate a focus on a discipline.

**Comment by gnu-lorien** [comment]
There are a variety of merits that change your health levels. When you have one of these, you go to the health levels section of your sheet and adjust it accordingly.
