### ISSUE TITLE
Login Error: "404 Not Found: POST"

### ISSUE THREAD

**Issue by ThyannaVoisine** [gnu-lorien/yorick#193]
Logging in through the following link: https://stagingpatron.undergroundtheater.org/, produces a "404 Not Found: POST" error with correct username and password. 

Correct username and password testing using the following link: https://patron.undergroundtheater.org/#

Windows OS
Chrome Browser

**Comment by gnu-lorien** [comment]
stagingpatron and patron use different accounts. You have to set up a new account on stagingpatron without using Facebook.
