### ISSUE TITLE
Change and Reset Password

### ISSUE THREAD

**Issue by krylyyk** [gnu-lorien/yorick#79]
There does not seem to be an option under Profile for a patron to change their password.

**Comment by Camanarch-ost** [comment]
Additionally, we need a password recovery function

**Comment by gnu-lorien** [comment]
There actually already is a password reset page. I wonder what happened to the link for it.

**Comment by gnu-lorien** [comment]
Partially finished. There's a way to reset your password from the login page but no way to change the password *other* than to do a reset.
