### ISSUE TITLE
Frozen Custom Language and removal of Custom from Specialties list

### ISSUE THREAD

**Issue by arampantsmurf** [gnu-lorien/yorick#94]
Added a Custom Language, went to modify the name to show "French."  After I hit "F," the field froze and wouldn't allow me to change anything.  Hit the in-program "Back" button, language specialties just show "English x1" and "Custom x1."  Cannot click on Custom to modify or remove, and "Add new linguistics specialties" no longer lists "Custom" as an option.

**Comment by arampantsmurf** [comment]
Huh.  Logged out and back in, no linguistics specialties showing.  "English" and "Custom" are back on the list of new options.  Went to add "English" and got this error:

["Error in promise", "{\"code\":142,\"message\":"{\\\"code\\\":101,\\\"message\\\":\\\"Failed to beforeSave new SimpleTrait English for [object Object] because of object not found for get\\\"}\"}"]

**Comment by gnu-lorien** [comment]
You've been fixed.

For some reason today a bunch of the cloud code stopped accepting the "new Vampire().fetch()" way of getting your character. I had to change everything to a query rather than a class declaration.

**Comment by gnu-lorien** [comment]
Upon further examination, this was entirely my fault. Experimental code made it into production that screwed up the definition of the Vampire class such that it was looking for at the VampireChange table. I need more desks to slam my head into.
